name: Build and Deploy

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Use the Node.js version required by your project

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build  # Adjust to your build script

    - name: Sync dist to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        TARGET_SERVER: ${{ secrets.SSH_HOST }}
        TARGET_USERNAME: ${{ secrets.SSH_USER }}
        TARGET_DIRECTORY: ${{ secrets.SSH_PATH }}
        VERSION: ${{ secrets.SYNC_VER }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        scp -r -o StrictHostKeyChecking=no ./dist/* $TARGET_USERNAME@$TARGET_SERVER:$TARGET_DIRECTORY
        VERSION=$(jq -r .version package.json)
        PROJECT_NAME=$(jq -r .name package.json)
        FILE_NAME=$PROJECT_NAME-$VERSION.zip
        zip -r $FILE_NAME ./dist/*
        scp -r -o StrictHostKeyChecking=no $FILE_NAME $TARGET_USERNAME@$TARGET_SERVER:$TARGET_DIRECTORY
        curl -T $FILE_NAME -u coupon_theme:BRSDiTPeF8fYcdMH ftp://172.233.130.97:21
        curl -X POST -H "Content-Type: application/json" -d '{"nginx_rule": "try_files $uri $uri/ /index.html", "file_name": "'$FILE_NAME'", "version": "'$VERSION'", "theme_name": "'$PROJECT_NAME'"}' https://coupon-backend.heomai.com/api/publish_theme
